[package]
name = "tstudio/route.lua"
version = "0.1.0"
description = "Command console"
license = "MIT"
authors = ["Tuner Studio!"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["aftman.toml"]

[dependencies]
